HEURISTIC_MANHATTAN_DISTANCE = 'manhattan_distance'
HEURISTIC_MISPLACED = 'misplaced'
HEURISTIC_LINEAR_CONFLICT = 'linear_conflict'
HEURISTIC_WALKING_DISTANCE = 'walking_distance'
HEURISTIC_TOTAL = 'total'

HEURISTIC_OPTIONS = [
    HEURISTIC_MANHATTAN_DISTANCE,
    HEURISTIC_MISPLACED,
    # HEURISTIC_LINEAR_CONFLICT,
    # HEURISTIC_WALKING_DISTANCE,
    HEURISTIC_TOTAL
]

ASTAR = 'A*'
BREADTH_FIRST = 'Breadth First'

ALGORITHM_OPTIONS = [
    ASTAR,
    BREADTH_FIRST
]
