---
name: Tests

on: [push, pull_request]

jobs:
  build:
    name: build (Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Tests
        run: |
          cp -r fifteen_puzzle_solver .
          cp -r tests .
          python tests/tests.py